version: '3'

services:
  server:
    build: ./server
    container_name: 'fvmc_dev_server'
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    env_file: 
      - .env

  frontend:
    stdin_open: true
    image: node:13.2.0
    container_name: 'fvmc_dev_client'
    command: ["/src/client/dev-nuxt.sh"]
    volumes:
      - .:/src
      - node_modules:/src/client/node_modules
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongodb:
    image: mongo:latest
    container_name: "fvmc_db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flask_db
      MONGODB_DATA_DIR: /var/lib/mongodb-data
      MONDODB_LOG_DIR: /dev/null
    volumes:
     - mongodb-data:/var/lib/mongodb-data
    ports:
      - "27017:27017"

volumes:
  app:
  mongodb-data:
  node_modules:

